/*
 *  generated by CSeq [ 0000 / 0000 ]
 * 
 *  instance version    {}
 *
 *  2019-02-21 15:22:01
 *
 *  params:
 *    -i TABLES/Table7/tbar_2_fenced.c, --viewSwitches 2, --rounds 1, 
 *
 */
#define __cs_MUTEX_INITIALIZER -1
#define __cs_COND_INITIALIZER -1
#define __cs_RWLOCK_INITIALIZER -1
#define __cs_BARRIER_SERIAL_THREAD 0
#define __cs_CANCEL_ASYNCHRONOUS 0
#define __cs_CANCEL_ENABLE 0
#define __cs_CANCEL_DEFERRED 0
#define __cs_CANCEL_DISABLE 0
#define __cs_CANCELED 0
#define __cs_CREATE_DETACHED 0
#define __cs_CREATE_JOINABLE 0
#define __cs_EXPLICIT_SCHED 0
#define __cs_INHERIT_SCHED 0
#define __cs_MUTEX_DEFAULT 0
#define __cs_MUTEX_ERRORCHECK 0
#define __cs_MUTEX_NORMAL 0
#define __cs_MUTEX_RECURSIVE 0
#define __cs_MUTEX_ROBUST 0
#define __cs_MUTEX_STALLED 0
#define __cs_ONCE_INIT 0
#define __cs_PRIO_INHERIT 0
#define __cs_PRIO_NONE 0
#define __cs_PRIO_PROTECT 0
#define __cs_PROCESS_SHARED 0
#define __cs_PROCESS_PRIVATE 0
#define __cs_SCOPE_PROCESS 0
#define __cs_SCOPE_SYSTEM 0
int __VERIFIER_nondet_int();
int nondet_int();
unsigned int __VERIFIER_nondet_uint();
unsigned int nondet_uint();
_Bool __VERIFIER_nondet_bool();
_Bool nondet_bool();
char __VERIFIER_nondet_char();
char nondet_char();
unsigned char __VERIFIER_nondet_uchar();
unsigned char nondet_uchar();
#define THREADS 2
#define ROUNDS 1
#define STOP_VOID(A) return;
#define STOP_NONVOID(A) return 0;
#define IF(T,A,B) if ((__cs_pc[T] > A) | (A >= __cs_pc_cs[T])) goto B;
                                        unsigned __CPROVER_bitvector[1] __cs_active_thread[3] = {1};
                                        unsigned __CPROVER_bitvector[3] __cs_pc[3];
                                        unsigned __CPROVER_bitvector[4] __cs_pc_cs[3];
                                        unsigned __CPROVER_bitvector[2] __cs_last_thread;
                                        unsigned __CPROVER_bitvector[3] __cs_thread_lines[3] = {2, 5, 5};
                                        unsigned __CPROVER_bitvector[8] var[2];
                                        unsigned __CPROVER_bitvector[8] childnotready_t[2];
                                        ;
                                        unsigned __CPROVER_bitvector[8] parentsense_t[2];
                                        ;
                                        unsigned __CPROVER_bitvector[8] tdiff0_t[2];
                                        ;
                                        unsigned __CPROVER_bitvector[8] tdiff1_t[2];
                                        ;
                                        unsigned __CPROVER_bitvector[8] __fence_var_t[2];
                                        ;
                                        unsigned __CPROVER_bitvector[8] _lazyra_s_RA = 0;
                                        const unsigned __CPROVER_bitvector[8] _lazyra_rounds = 2;
                                        unsigned __CPROVER_bitvector[8] _lazyra_index_used = 0;
                                        unsigned __CPROVER_bitvector[1] _lazyra_unavail_childnotready[5];
                                        unsigned __CPROVER_bitvector[1] _lazyra_upd_childnotready[5];
                                        int childnotready_view[3];
                                        int childnotready_values[5];
                                        unsigned __CPROVER_bitvector[8] childnotready_view_t[3];
                                        unsigned __CPROVER_bitvector[1] childnotready_view_l[3];
                                        unsigned __CPROVER_bitvector[1] _lazyra_unavail_parentsense[5];
                                        unsigned __CPROVER_bitvector[1] _lazyra_upd_parentsense[5];
                                        int parentsense_view[3];
                                        int parentsense_values[5];
                                        unsigned __CPROVER_bitvector[8] parentsense_view_t[3];
                                        unsigned __CPROVER_bitvector[1] parentsense_view_l[3];
                                        unsigned __CPROVER_bitvector[1] _lazyra_unavail_tdiff0[5];
                                        unsigned __CPROVER_bitvector[1] _lazyra_upd_tdiff0[5];
                                        int tdiff0_view[3];
                                        int tdiff0_values[5];
                                        unsigned __CPROVER_bitvector[8] tdiff0_view_t[3];
                                        unsigned __CPROVER_bitvector[1] tdiff0_view_l[3];
                                        unsigned __CPROVER_bitvector[1] _lazyra_unavail_tdiff1[5];
                                        unsigned __CPROVER_bitvector[1] _lazyra_upd_tdiff1[5];
                                        int tdiff1_view[3];
                                        int tdiff1_values[5];
                                        unsigned __CPROVER_bitvector[8] tdiff1_view_t[3];
                                        unsigned __CPROVER_bitvector[1] tdiff1_view_l[3];
                                        unsigned __CPROVER_bitvector[1] _lazyra_unavail___fence_var[5];
                                        unsigned __CPROVER_bitvector[1] _lazyra_upd___fence_var[5];
                                        int __fence_var_view[3];
                                        int __fence_var_values[5];
                                        unsigned __CPROVER_bitvector[8] __fence_var_view_t[3];
                                        unsigned __CPROVER_bitvector[1] __fence_var_view_l[3];
                                        void merge_views_ra(unsigned int t1, unsigned int t2){
                                        if(t1==0){
                                        (childnotready_view_l)[t2] = 1;
                                        }
                                        __CPROVER_assume((childnotready_view_l)[t1]);
                                        __CPROVER_assume((childnotready_view_l)[t2]);
                                        if(childnotready_view_t[t2] <= childnotready_view_t[t1]){
                                        childnotready_view_t[t2] = childnotready_view_t[t1];
                                        childnotready_view[t2] = childnotready_view[t1];
                                        }
                                        if(t1==0){
                                        (parentsense_view_l)[t2] = 1;
                                        }
                                        __CPROVER_assume((parentsense_view_l)[t1]);
                                        __CPROVER_assume((parentsense_view_l)[t2]);
                                        if(parentsense_view_t[t2] <= parentsense_view_t[t1]){
                                        parentsense_view_t[t2] = parentsense_view_t[t1];
                                        parentsense_view[t2] = parentsense_view[t1];
                                        }
                                        if(t1==0){
                                        (tdiff0_view_l)[t2] = 1;
                                        }
                                        __CPROVER_assume((tdiff0_view_l)[t1]);
                                        __CPROVER_assume((tdiff0_view_l)[t2]);
                                        if(tdiff0_view_t[t2] <= tdiff0_view_t[t1]){
                                        tdiff0_view_t[t2] = tdiff0_view_t[t1];
                                        tdiff0_view[t2] = tdiff0_view[t1];
                                        }
                                        if(t1==0){
                                        (tdiff1_view_l)[t2] = 1;
                                        }
                                        __CPROVER_assume((tdiff1_view_l)[t1]);
                                        __CPROVER_assume((tdiff1_view_l)[t2]);
                                        if(tdiff1_view_t[t2] <= tdiff1_view_t[t1]){
                                        tdiff1_view_t[t2] = tdiff1_view_t[t1];
                                        tdiff1_view[t2] = tdiff1_view[t1];
                                        }
                                        if(t1==0){
                                        (__fence_var_view_l)[t2] = 1;
                                        }
                                        __CPROVER_assume((__fence_var_view_l)[t1]);
                                        __CPROVER_assume((__fence_var_view_l)[t2]);
                                        if(__fence_var_view_t[t2] <= __fence_var_view_t[t1]){
                                        __fence_var_view_t[t2] = __fence_var_view_t[t1];
                                        __fence_var_view[t2] = __fence_var_view[t1];
                                        }
                                        }
                                        void publish_message(int thread_num, int var_num){
                                        __CPROVER_assume(_lazyra_index_used<_lazyra_rounds);
                                        __CPROVER_assume((childnotready_view_l)[thread_num]);
                                        __CPROVER_assume((parentsense_view_l)[thread_num]);
                                        __CPROVER_assume((tdiff0_view_l)[thread_num]);
                                        __CPROVER_assume((tdiff1_view_l)[thread_num]);
                                        __CPROVER_assume((__fence_var_view_l)[thread_num]);
                                        (childnotready_t)[_lazyra_index_used] = childnotready_view_t[thread_num];
                                        (parentsense_t)[_lazyra_index_used] = parentsense_view_t[thread_num];
                                        (tdiff0_t)[_lazyra_index_used] = tdiff0_view_t[thread_num];
                                        (tdiff1_t)[_lazyra_index_used] = tdiff1_view_t[thread_num];
                                        (__fence_var_t)[_lazyra_index_used] = __fence_var_view_t[thread_num];
                                        var[_lazyra_index_used]=var_num;
                                        _lazyra_index_used = _lazyra_index_used + 1;
                                        }
                                        void update_view(int thread_num, int var_num, unsigned __CPROVER_bitvector[8] message_num){
                                        __CPROVER_assume((childnotready_view_l)[thread_num]);
                                        __CPROVER_assume((parentsense_view_l)[thread_num]);
                                        __CPROVER_assume((tdiff0_view_l)[thread_num]);
                                        __CPROVER_assume((tdiff1_view_l)[thread_num]);
                                        __CPROVER_assume((__fence_var_view_l)[thread_num]);
                                        if((childnotready_t)[message_num]>(childnotready_view_t)[thread_num]){
                                        childnotready_view[thread_num] = childnotready_values[childnotready_t[message_num]];
                                        (childnotready_view_t)[thread_num] = (childnotready_t)[message_num];
                                        }
                                        if((parentsense_t)[message_num]>(parentsense_view_t)[thread_num]){
                                        parentsense_view[thread_num] = parentsense_values[parentsense_t[message_num]];
                                        (parentsense_view_t)[thread_num] = (parentsense_t)[message_num];
                                        }
                                        if((tdiff0_t)[message_num]>(tdiff0_view_t)[thread_num]){
                                        tdiff0_view[thread_num] = tdiff0_values[tdiff0_t[message_num]];
                                        (tdiff0_view_t)[thread_num] = (tdiff0_t)[message_num];
                                        }
                                        if((tdiff1_t)[message_num]>(tdiff1_view_t)[thread_num]){
                                        tdiff1_view[thread_num] = tdiff1_values[tdiff1_t[message_num]];
                                        (tdiff1_view_t)[thread_num] = (tdiff1_t)[message_num];
                                        }
                                        if((__fence_var_t)[message_num]>(__fence_var_view_t)[thread_num]){
                                        __fence_var_view[thread_num] = __fence_var_values[__fence_var_t[message_num]];
                                        (__fence_var_view_t)[thread_num] = (__fence_var_t)[message_num];
                                        }
                                        }
                                        void *__cs_safe_malloc(unsigned int __cs_size)
                                        {
                                        void *__cs_ptr = (malloc(__cs_size));
                                        return __cs_ptr;
                                        }
                                        void __cs_init_scalar(void *__cs_var, unsigned int __cs_size)
                                        {
                                        if (__cs_size == (sizeof(int)))
                                        *((int *) __cs_var) = nondet_int();
                                                else
                                                {
                                        __cs_var = malloc(__cs_size);
                                                }
                                        }
                                        void __CSEQ_message(char *__cs_message)
                                        {
                                                ;
                                        }
                                        typedef int __cs_t;
                                        void *__cs_threadargs[3];
                                        void *__cs_thread_joinargs[3];
                                        int __cs_create(__cs_t *__cs_new_thread_id, void *__cs_attr, void *(*__cs_thread_function)(void *), void *__cs_arg, int __cs_threadID)
                                        {
                                        if (__cs_threadID > THREADS)
                                                        return 0;
                                        *__cs_new_thread_id = __cs_threadID;
                                        __cs_active_thread[__cs_threadID] = 1;
                                        __cs_threadargs[__cs_threadID] = __cs_arg;
                                        __CSEQ_message("thread spawned");
                                        return 0;
                                        }
                                        int __cs_join(__cs_t __cs_id, void **__cs_value_ptr)
                                        {
                                        __CPROVER_assume(__cs_pc[__cs_id] == __cs_thread_lines[__cs_id]);
                                        *__cs_value_ptr = __cs_thread_joinargs[__cs_id];
                                        return 0;
                                        }
                                        int __cs_exit(void *__cs_value_ptr, unsigned int __cs_thread_index)
                                        {
                                        __cs_thread_joinargs[__cs_thread_index] = __cs_value_ptr;
                                        return 0;
                                        }
                                        int __cs_self(void)
                                        {
                                                return 1;
                                        }
                                        typedef int __cs_mutex_t;
                                        int __cs_mutex_init(__cs_mutex_t *__cs_m, int __cs_val)
                                        {
                                        *__cs_m = -1;
                                        return 0;
                                        }
                                        int __cs_mutex_destroy(__cs_mutex_t *__cs_mutex_to_destroy)
                                        {
                                        __CPROVER_assert((*__cs_mutex_to_destroy) != 0, "attempt to destroy an uninitialized mutex");
                                        __CPROVER_assert((*__cs_mutex_to_destroy) != (-2), "attempt to destroy a previously destroyed mutex");
                                        __CPROVER_assert((*__cs_mutex_to_destroy) == (-1), "attempt to destroy a locked mutex");
                                        *__cs_mutex_to_destroy = -2;
                                        __CSEQ_message("lock destroyed");
                                        return 0;
                                        }
                                        int __cs_mutex_lock(__cs_mutex_t *__cs_mutex_to_lock, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assert((*__cs_mutex_to_lock) != 0, "attempt to lock an uninitialized mutex");
                                        __CPROVER_assert((*__cs_mutex_to_lock) != (-2), "attempt to lock a destroyed mutex");
                                        __CPROVER_assume((*__cs_mutex_to_lock) == (-1));
                                        *__cs_mutex_to_lock = __cs_thread_index + 1;
                                        __CSEQ_message("lock acquired");
                                        return 0;
                                        }
                                        int __cs_mutex_unlock(__cs_mutex_t *__cs_mutex_to_unlock, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assert((*__cs_mutex_to_unlock) != 0, "attempt to unlock an uninitialized mutex");
                                        __CPROVER_assert((*__cs_mutex_to_unlock) != (-2), "attempt to unlock a destroyed mutex");
                                        __CPROVER_assume((*__cs_mutex_to_unlock) == (__cs_thread_index + 1));
                                        *__cs_mutex_to_unlock = -1;
                                        __CSEQ_message("lock released");
                                        return 0;
                                        }
                                        typedef int __cs_cond_t;
                                        int __cs_cond_init(__cs_cond_t *__cs_cond_to_init, void *__cs_attr)
                                        {
                                        *__cs_cond_to_init = -1;
                                        return 0;
                                        }
                                        int __cs_cond_destroy(__cs_cond_t *__cs_cond_to_destroy)
                                        {
                                        *__cs_cond_to_destroy = -2;
                                        return 0;
                                        }
                                        int __cs_cond_wait_1(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assert((*__cs_cond_to_wait_for) != 0, "attempt to use an uninitialized conditional variable");
                                        __CPROVER_assert((*__cs_cond_to_wait_for) != (-2), "attempt to use a destroyed conditional variable");
                                        __cs_mutex_unlock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_wait_2(__cs_cond_t *__cs_cond_to_wait_for, __cs_mutex_t *__cs_m, unsigned int __cs_thread_index)
                                        {
                                        __CPROVER_assume((*__cs_cond_to_wait_for) == 1);
                                        __cs_mutex_lock(__cs_m, __cs_thread_index);
                                        return 0;
                                        }
                                        int __cs_cond_signal(__cs_cond_t *__cs_cond_to_signal)
                                        {
                                        *__cs_cond_to_signal = 1;
                                        __CSEQ_message("conditional variable signal");
                                        return 0;
                                        }
                                        int __cs_cond_broadcast(__cs_cond_t *__cs_cond_to_broadcast)
                                        {
                                        *__cs_cond_to_broadcast = 1;
                                        __CSEQ_message("conditional variable broadcast");
                                        return 0;
                                        }
                                        typedef struct __cs_barrier_t
                                        {
                                        unsigned int init;
                                        unsigned int current;
                                        } __cs_barrier_t;
                                        int __cs_barrier_init(__cs_barrier_t *__cs_barrier_to_init, void *__cs_attr, unsigned int count)
                                        {
                                        __CPROVER_assert(count > 0, "count must be greater than 0");
                                        __cs_barrier_to_init->current = count;
                                        __cs_barrier_to_init->init = count;
                                        return 0;
                                        }
                                        int __cs_barrier_destroy(__cs_barrier_t *__cs_barrier_to_destroy)
                                        {
                                        __cs_barrier_to_destroy->init = -1;
                                        __cs_barrier_to_destroy->current = -1;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_1(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assert(__cs_barrier_to_wait->init > 0, "attempt to use an uninitialized barrier variable");
                                        __cs_barrier_to_wait->current--;
                                        return 0;
                                        }
                                        int __cs_barrier_wait_2(__cs_barrier_t *__cs_barrier_to_wait)
                                        {
                                        __CPROVER_assert(__cs_barrier_to_wait->init > 0, "attempt to use an uninitialized barrier variable");
                                        __CPROVER_assume(__cs_barrier_to_wait->current == 0);
                                        __cs_barrier_to_wait->current = __cs_barrier_to_wait->init;
                                        return 0;
                                        }
                                        typedef int __cs_attr_t;
                                        struct sched_param
                                        {
                                        int sched_priority;
                                        };
                                        int __cs_attr_init(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_destroy(__cs_attr_t *t)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getdetachstate(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getguardsize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getinheritsched(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedparam(const __cs_attr_t *t, struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getschedpolicy(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getscope(const __cs_attr_t *t, int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstackaddr(const __cs_attr_t *t, void **s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_getstacksize(const __cs_attr_t *t, unsigned int *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setdetachstate(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setguardsize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setinheritsched(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedparam(__cs_attr_t *t, const struct sched_param *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setschedpolicy(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setscope(__cs_attr_t *t, int s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstackaddr(__cs_attr_t *t, void *s)
                                        {
                                                return 0;
                                        }
                                        int __cs_attr_setstacksize(__cs_attr_t *t, unsigned int s)
                                        {
                                                return 0;
                                        }
                                        int childnotready = (1);
                                        int parentsense = (0);
                                        int tdiff0 = (0);
                                        int tdiff1 = (0);
                                        int __fence_var;
                                        void *t0_0(void *__cs_param_t0___cs_unused)
                                        {
tt0_0_0: IF(1,0,tt0_0_1)
                                        ;
                                        static unsigned int __cs_local_t0__ra_non_det_int_var;
                                        static _Bool __cs_local_t0__ra_non_det_bool_var;
                                        int __cs_local_t0__int_update_helper_var;
                                                {
                                        static int __cs_local_t0_rsense;
                                        __cs_local_t0_rsense = 1;
                                        static int __cs_local_t0_rchildnotready;
                                        __cs_local_t0_rchildnotready = -1;
                                        static int __cs_local_t0_rtdiff1;
                                        __cs_local_t0_rtdiff1 = -1;
                                        while (1)
                                                        {
                                        tdiff0_view[1] = 1;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var > tdiff0_view_t[1]);
                                        __CPROVER_assume(!_lazyra_unavail_tdiff0[__cs_local_t0__ra_non_det_int_var]);
                                        _lazyra_unavail_tdiff0[__cs_local_t0__ra_non_det_int_var] = 1;
                                        _lazyra_upd_tdiff0[__cs_local_t0__ra_non_det_int_var] = 1;
                                        tdiff0_view_t[1] = __cs_local_t0__ra_non_det_int_var;
                                        tdiff0_view_l[1] = 1;
                                        tdiff0_values[__cs_local_t0__ra_non_det_int_var] = tdiff0_view[1];
                                        if (nondet_bool())
                                                                        {
                                        publish_message(1, 3);
                                                                        }
                                                                }
                                                                else
                                        tdiff0_view_l[1] = 0;
                                        ;
                                        ;
                                        ;
                                                                ;
                                        __cs_local_t0__int_update_helper_var = 0;
tt0_0_1: IF(1,1,tt0_0_2)
                                        __cs_local_t0__ra_non_det_bool_var = 0;
                                        if (nondet_bool())
                                                                {
                                        if (__fence_var_view_l[1])
                                                                        {
                                        __cs_local_t0__ra_non_det_bool_var = 1;
                                                                        }
                                                                }
                                                                else
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(5 == var[__cs_local_t0__ra_non_det_int_var]);
                                        __CPROVER_assume(__fence_var_t[__cs_local_t0__ra_non_det_int_var] >= __fence_var_view_t[1]);
                                        update_view(1, 5, __cs_local_t0__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                        __cs_local_t0__ra_non_det_bool_var = 1;
                                                                }
                                        if (__cs_local_t0__ra_non_det_bool_var == 1)
                                                                {
                                        __CPROVER_assume(_lazyra_upd___fence_var[__fence_var_view_t[1]]);
                                        _lazyra_upd___fence_var[__fence_var_view_t[1]] = 0;
                                                                }
                                        __fence_var_view[1] = __cs_local_t0__int_update_helper_var;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        if (__cs_local_t0__ra_non_det_bool_var)
                                                                        {
                                        __cs_local_t0__ra_non_det_int_var = __fence_var_view_t[1] + 1;
                                                                        }
                                        __fence_var_values[__cs_local_t0__ra_non_det_int_var] = __fence_var_view[1];
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var > __fence_var_view_t[1]);
                                        __CPROVER_assume(!_lazyra_unavail___fence_var[__cs_local_t0__ra_non_det_int_var]);
                                        _lazyra_unavail___fence_var[__cs_local_t0__ra_non_det_int_var] = 1;
                                        _lazyra_upd___fence_var[__cs_local_t0__ra_non_det_int_var] = 1;
                                        __fence_var_view_t[1] = __cs_local_t0__ra_non_det_int_var;
                                        __fence_var_view_l[1] = 1;
                                        if (nondet_bool())
                                                                        {
                                        publish_message(1, 5);
                                                                        }
                                                                }
                                                                else
                                        __fence_var_view_l[1] = 0;
                                        ;
tt0_0_2: IF(1,2,tt0_0_3)
                                        ;
                                        if (nondet_bool())
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(1 == var[__cs_local_t0__ra_non_det_int_var]);
                                        __CPROVER_assume(childnotready_t[__cs_local_t0__ra_non_det_int_var] >= childnotready_view_t[1]);
                                        update_view(1, 1, __cs_local_t0__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                                                }
                                        ;
                                        __cs_local_t0_rchildnotready = childnotready_view[1];
                                        __CPROVER_assume(__cs_local_t0_rchildnotready == 0);
                                        childnotready_view[1] = 1;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var > childnotready_view_t[1]);
                                        __CPROVER_assume(!_lazyra_unavail_childnotready[__cs_local_t0__ra_non_det_int_var]);
                                        _lazyra_unavail_childnotready[__cs_local_t0__ra_non_det_int_var] = 1;
                                        _lazyra_upd_childnotready[__cs_local_t0__ra_non_det_int_var] = 1;
                                        childnotready_view_t[1] = __cs_local_t0__ra_non_det_int_var;
                                        childnotready_view_l[1] = 1;
                                        childnotready_values[__cs_local_t0__ra_non_det_int_var] = childnotready_view[1];
                                        if (nondet_bool())
                                                                        {
                                        publish_message(1, 1);
                                                                        }
                                                                }
                                                                else
                                        childnotready_view_l[1] = 0;
                                        ;
                                        ;
                                        ;
                                                                ;
tt0_0_3: IF(1,3,tt0_0_4)
                                        ;
                                        parentsense_view[1] = __cs_local_t0_rsense;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var > parentsense_view_t[1]);
                                        __CPROVER_assume(!_lazyra_unavail_parentsense[__cs_local_t0__ra_non_det_int_var]);
                                        _lazyra_unavail_parentsense[__cs_local_t0__ra_non_det_int_var] = 1;
                                        _lazyra_upd_parentsense[__cs_local_t0__ra_non_det_int_var] = 1;
                                        parentsense_view_t[1] = __cs_local_t0__ra_non_det_int_var;
                                        parentsense_view_l[1] = 1;
                                        parentsense_values[__cs_local_t0__ra_non_det_int_var] = parentsense_view[1];
                                        if (nondet_bool())
                                                                        {
                                        publish_message(1, 2);
                                                                        }
                                                                }
                                                                else
                                        parentsense_view_l[1] = 0;
                                        ;
                                        ;
                                        ;
                                                                ;
tt0_0_4: IF(1,4,tt0_0_5)
                                        ;
                                        __cs_local_t0_rsense = 1 - __cs_local_t0_rsense;
                                        __cs_local_t0__int_update_helper_var = 0;
                                        __cs_local_t0__ra_non_det_bool_var = 0;
                                        if (nondet_bool())
                                                                {
                                        if (__fence_var_view_l[1])
                                                                        {
                                        __cs_local_t0__ra_non_det_bool_var = 1;
                                                                        }
                                                                }
                                                                else
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(5 == var[__cs_local_t0__ra_non_det_int_var]);
                                        __CPROVER_assume(__fence_var_t[__cs_local_t0__ra_non_det_int_var] >= __fence_var_view_t[1]);
                                        update_view(1, 5, __cs_local_t0__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                        __cs_local_t0__ra_non_det_bool_var = 1;
                                                                }
                                        if (__cs_local_t0__ra_non_det_bool_var == 1)
                                                                {
                                        __CPROVER_assume(_lazyra_upd___fence_var[__fence_var_view_t[1]]);
                                        _lazyra_upd___fence_var[__fence_var_view_t[1]] = 0;
                                                                }
                                        __fence_var_view[1] = __cs_local_t0__int_update_helper_var;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        if (__cs_local_t0__ra_non_det_bool_var)
                                                                        {
                                        __cs_local_t0__ra_non_det_int_var = __fence_var_view_t[1] + 1;
                                                                        }
                                        __fence_var_values[__cs_local_t0__ra_non_det_int_var] = __fence_var_view[1];
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var > __fence_var_view_t[1]);
                                        __CPROVER_assume(!_lazyra_unavail___fence_var[__cs_local_t0__ra_non_det_int_var]);
                                        _lazyra_unavail___fence_var[__cs_local_t0__ra_non_det_int_var] = 1;
                                        _lazyra_upd___fence_var[__cs_local_t0__ra_non_det_int_var] = 1;
                                        __fence_var_view_t[1] = __cs_local_t0__ra_non_det_int_var;
                                        __fence_var_view_l[1] = 1;
                                        if (nondet_bool())
                                                                        {
                                        publish_message(1, 5);
                                                                        }
                                                                }
                                                                else
                                        __fence_var_view_l[1] = 0;
                                        ;
                                        if (nondet_bool())
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t0__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t0__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(4 == var[__cs_local_t0__ra_non_det_int_var]);
                                        __CPROVER_assume(tdiff1_t[__cs_local_t0__ra_non_det_int_var] >= tdiff1_view_t[1]);
                                        update_view(1, 4, __cs_local_t0__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                                                }
                                        ;
                                        __cs_local_t0_rtdiff1 = tdiff1_view[1];
                                        assert(__cs_local_t0_rtdiff1 != 0);
                                                        }
                                        ;
                                        ;
                                        __exit_t0:
                                                        __CPROVER_assume(__cs_pc_cs[1] >= 5);
                                        ;
                                                        ;
tt0_0_5: 
                                        __cs_exit(0, 1);
                                                }
                                        ;
                                        }
                                        void *t1_0(void *__cs_param_t1___cs_unused)
                                        {
tt1_0_0: IF(2,0,tt1_0_1)
                                        ;
                                        static unsigned int __cs_local_t1__ra_non_det_int_var;
                                        static _Bool __cs_local_t1__ra_non_det_bool_var;
                                        int __cs_local_t1__int_update_helper_var;
                                                {
                                        static int __cs_local_t1_rsense;
                                        __cs_local_t1_rsense = 1;
                                        static int __cs_local_t1_rtdiff0;
                                        __cs_local_t1_rtdiff0 = -1;
                                        static int __cs_local_t1_rparentsense;
                                        __cs_local_t1_rparentsense = -1;
                                        while (1)
                                                        {
                                        tdiff1_view[2] = 1;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var > tdiff1_view_t[2]);
                                        __CPROVER_assume(!_lazyra_unavail_tdiff1[__cs_local_t1__ra_non_det_int_var]);
                                        _lazyra_unavail_tdiff1[__cs_local_t1__ra_non_det_int_var] = 1;
                                        _lazyra_upd_tdiff1[__cs_local_t1__ra_non_det_int_var] = 1;
                                        tdiff1_view_t[2] = __cs_local_t1__ra_non_det_int_var;
                                        tdiff1_view_l[2] = 1;
                                        tdiff1_values[__cs_local_t1__ra_non_det_int_var] = tdiff1_view[2];
                                        if (nondet_bool())
                                                                        {
                                        publish_message(2, 4);
                                                                        }
                                                                }
                                                                else
                                        tdiff1_view_l[2] = 0;
                                        ;
                                        ;
                                        ;
                                                                ;
                                        __cs_local_t1__int_update_helper_var = 0;
tt1_0_1: IF(2,1,tt1_0_2)
                                        __cs_local_t1__ra_non_det_bool_var = 0;
                                        if (nondet_bool())
                                                                {
                                        if (__fence_var_view_l[2])
                                                                        {
                                        __cs_local_t1__ra_non_det_bool_var = 1;
                                                                        }
                                                                }
                                                                else
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(5 == var[__cs_local_t1__ra_non_det_int_var]);
                                        __CPROVER_assume(__fence_var_t[__cs_local_t1__ra_non_det_int_var] >= __fence_var_view_t[2]);
                                        update_view(2, 5, __cs_local_t1__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                        __cs_local_t1__ra_non_det_bool_var = 1;
                                                                }
                                        if (__cs_local_t1__ra_non_det_bool_var == 1)
                                                                {
                                        __CPROVER_assume(_lazyra_upd___fence_var[__fence_var_view_t[2]]);
                                        _lazyra_upd___fence_var[__fence_var_view_t[2]] = 0;
                                                                }
                                        __fence_var_view[2] = __cs_local_t1__int_update_helper_var;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        if (__cs_local_t1__ra_non_det_bool_var)
                                                                        {
                                        __cs_local_t1__ra_non_det_int_var = __fence_var_view_t[2] + 1;
                                                                        }
                                        __fence_var_values[__cs_local_t1__ra_non_det_int_var] = __fence_var_view[2];
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var > __fence_var_view_t[2]);
                                        __CPROVER_assume(!_lazyra_unavail___fence_var[__cs_local_t1__ra_non_det_int_var]);
                                        _lazyra_unavail___fence_var[__cs_local_t1__ra_non_det_int_var] = 1;
                                        _lazyra_upd___fence_var[__cs_local_t1__ra_non_det_int_var] = 1;
                                        __fence_var_view_t[2] = __cs_local_t1__ra_non_det_int_var;
                                        __fence_var_view_l[2] = 1;
                                        if (nondet_bool())
                                                                        {
                                        publish_message(2, 5);
                                                                        }
                                                                }
                                                                else
                                        __fence_var_view_l[2] = 0;
                                        ;
tt1_0_2: IF(2,2,tt1_0_3)
                                        ;
                                        childnotready_view[2] = 0;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var > childnotready_view_t[2]);
                                        __CPROVER_assume(!_lazyra_unavail_childnotready[__cs_local_t1__ra_non_det_int_var]);
                                        _lazyra_unavail_childnotready[__cs_local_t1__ra_non_det_int_var] = 1;
                                        _lazyra_upd_childnotready[__cs_local_t1__ra_non_det_int_var] = 1;
                                        childnotready_view_t[2] = __cs_local_t1__ra_non_det_int_var;
                                        childnotready_view_l[2] = 1;
                                        childnotready_values[__cs_local_t1__ra_non_det_int_var] = childnotready_view[2];
                                        if (nondet_bool())
                                                                        {
                                        publish_message(2, 1);
                                                                        }
                                                                }
                                                                else
                                        childnotready_view_l[2] = 0;
                                        ;
                                        ;
                                        ;
                                                                ;
                                        __cs_local_t1__int_update_helper_var = 0;
tt1_0_3: IF(2,3,tt1_0_4)
                                        __cs_local_t1__ra_non_det_bool_var = 0;
                                        if (nondet_bool())
                                                                {
                                        if (__fence_var_view_l[2])
                                                                        {
                                        __cs_local_t1__ra_non_det_bool_var = 1;
                                                                        }
                                                                }
                                                                else
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(5 == var[__cs_local_t1__ra_non_det_int_var]);
                                        __CPROVER_assume(__fence_var_t[__cs_local_t1__ra_non_det_int_var] >= __fence_var_view_t[2]);
                                        update_view(2, 5, __cs_local_t1__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                        __cs_local_t1__ra_non_det_bool_var = 1;
                                                                }
                                        if (__cs_local_t1__ra_non_det_bool_var == 1)
                                                                {
                                        __CPROVER_assume(_lazyra_upd___fence_var[__fence_var_view_t[2]]);
                                        _lazyra_upd___fence_var[__fence_var_view_t[2]] = 0;
                                                                }
                                        __fence_var_view[2] = __cs_local_t1__int_update_helper_var;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        if (__cs_local_t1__ra_non_det_bool_var)
                                                                        {
                                        __cs_local_t1__ra_non_det_int_var = __fence_var_view_t[2] + 1;
                                                                        }
                                        __fence_var_values[__cs_local_t1__ra_non_det_int_var] = __fence_var_view[2];
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var > __fence_var_view_t[2]);
                                        __CPROVER_assume(!_lazyra_unavail___fence_var[__cs_local_t1__ra_non_det_int_var]);
                                        _lazyra_unavail___fence_var[__cs_local_t1__ra_non_det_int_var] = 1;
                                        _lazyra_upd___fence_var[__cs_local_t1__ra_non_det_int_var] = 1;
                                        __fence_var_view_t[2] = __cs_local_t1__ra_non_det_int_var;
                                        __fence_var_view_l[2] = 1;
                                        if (nondet_bool())
                                                                        {
                                        publish_message(2, 5);
                                                                        }
                                                                }
                                                                else
                                        __fence_var_view_l[2] = 0;
                                        ;
tt1_0_4: IF(2,4,tt1_0_5)
                                        ;
                                        if (nondet_bool())
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(2 == var[__cs_local_t1__ra_non_det_int_var]);
                                        __CPROVER_assume(parentsense_t[__cs_local_t1__ra_non_det_int_var] >= parentsense_view_t[2]);
                                        update_view(2, 2, __cs_local_t1__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                                                }
                                        ;
                                        __cs_local_t1_rparentsense = parentsense_view[2];
                                        __CPROVER_assume(__cs_local_t1_rparentsense == __cs_local_t1_rsense);
                                        __cs_local_t1_rsense = 1 - __cs_local_t1_rsense;
                                        __cs_local_t1__int_update_helper_var = 0;
                                        __cs_local_t1__ra_non_det_bool_var = 0;
                                        if (nondet_bool())
                                                                {
                                        if (__fence_var_view_l[2])
                                                                        {
                                        __cs_local_t1__ra_non_det_bool_var = 1;
                                                                        }
                                                                }
                                                                else
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(5 == var[__cs_local_t1__ra_non_det_int_var]);
                                        __CPROVER_assume(__fence_var_t[__cs_local_t1__ra_non_det_int_var] >= __fence_var_view_t[2]);
                                        update_view(2, 5, __cs_local_t1__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                        __cs_local_t1__ra_non_det_bool_var = 1;
                                                                }
                                        if (__cs_local_t1__ra_non_det_bool_var == 1)
                                                                {
                                        __CPROVER_assume(_lazyra_upd___fence_var[__fence_var_view_t[2]]);
                                        _lazyra_upd___fence_var[__fence_var_view_t[2]] = 0;
                                                                }
                                        __fence_var_view[2] = __cs_local_t1__int_update_helper_var;
                                        if (nondet_bool())
                                                                {
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        if (__cs_local_t1__ra_non_det_bool_var)
                                                                        {
                                        __cs_local_t1__ra_non_det_int_var = __fence_var_view_t[2] + 1;
                                                                        }
                                        __fence_var_values[__cs_local_t1__ra_non_det_int_var] = __fence_var_view[2];
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var <= (2 * _lazyra_rounds));
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var > __fence_var_view_t[2]);
                                        __CPROVER_assume(!_lazyra_unavail___fence_var[__cs_local_t1__ra_non_det_int_var]);
                                        _lazyra_unavail___fence_var[__cs_local_t1__ra_non_det_int_var] = 1;
                                        _lazyra_upd___fence_var[__cs_local_t1__ra_non_det_int_var] = 1;
                                        __fence_var_view_t[2] = __cs_local_t1__ra_non_det_int_var;
                                        __fence_var_view_l[2] = 1;
                                        if (nondet_bool())
                                                                        {
                                        publish_message(2, 5);
                                                                        }
                                                                }
                                                                else
                                        __fence_var_view_l[2] = 0;
                                        ;
                                        if (nondet_bool())
                                                                {
                                        __CPROVER_assume(_lazyra_s_RA < _lazyra_rounds);
                                        __cs_local_t1__ra_non_det_int_var = nondet_uint();
                                        __CPROVER_assume(__cs_local_t1__ra_non_det_int_var < _lazyra_index_used);
                                        __CPROVER_assume(3 == var[__cs_local_t1__ra_non_det_int_var]);
                                        __CPROVER_assume(tdiff0_t[__cs_local_t1__ra_non_det_int_var] >= tdiff0_view_t[2]);
                                        update_view(2, 3, __cs_local_t1__ra_non_det_int_var);
                                        _lazyra_s_RA = _lazyra_s_RA + 1;
                                                                }
                                        ;
                                        __cs_local_t1_rtdiff0 = tdiff0_view[2];
                                        assert(__cs_local_t1_rtdiff0 != 0);
                                                        }
                                        ;
                                        ;
                                        __exit_t1:
                                                        __CPROVER_assume(__cs_pc_cs[2] >= 5);
                                        ;
                                                        ;
tt1_0_5: 
                                        __cs_exit(0, 2);
                                                }
                                        ;
                                        }
                                        int main_thread(void)
                                        {
IF(0,0,tmain_1)
                                        unsigned int __cs_local_main_helper_temporary = (1);
                                        _lazyra_unavail_childnotready[0] = 1;
                                        _lazyra_upd_childnotready[0] = 1;
                                        _lazyra_unavail_parentsense[0] = 1;
                                        _lazyra_upd_parentsense[0] = 1;
                                        _lazyra_unavail_tdiff0[0] = 1;
                                        _lazyra_upd_tdiff0[0] = 1;
                                        _lazyra_unavail_tdiff1[0] = 1;
                                        _lazyra_upd_tdiff1[0] = 1;
                                        _lazyra_unavail___fence_var[0] = 1;
                                        _lazyra_upd___fence_var[0] = 1;
                                        childnotready_view_l[0] = 1;
                                        parentsense_view_l[0] = 1;
                                        tdiff0_view_l[0] = 1;
                                        tdiff1_view_l[0] = 1;
                                        __fence_var_view_l[0] = 1;
                                        static unsigned int __cs_local_main__ra_non_det_int_var;
                                        static _Bool __cs_local_main__ra_non_det_bool_var;
                                        int __cs_local_main__int_update_helper_var;
                                                {
                                        childnotready_view[0] = 1;
                                        static __cs_t __cs_local_main__cs_tdiff0;
                                        ;
                                                        ;
                                        static __cs_t __cs_local_main__cs_tdiff1;
                                        ;
                                                        ;
                                        merge_views_ra(0, 1);
                                        __cs_create(&__cs_local_main__cs_tdiff0, 0, t0_0, 0, 1);
tmain_1: IF(0,1,tmain_2)
                                        merge_views_ra(0, 2);
                                        __cs_create(&__cs_local_main__cs_tdiff1, 0, t1_0, 0, 2);
                                        goto __exit_main;
                                                        ;
                                        __exit_main:
                                                        __CPROVER_assume(__cs_pc_cs[0] >= 2);
                                        ;
                                                        ;
tmain_2: 
                                        __cs_exit(0, 0);
                                                }
                                        ;
                                        }
                                        int main(void)
                                        {
/* round  0 */
/* main */
                                        unsigned int __cs_tmp_t0_r0;
                                        __cs_pc_cs[0] = __cs_tmp_t0_r0;
                                        __CPROVER_assume(__cs_pc_cs[0] > 0);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 2);
                                        main_thread();
                                        __cs_pc[0] = __cs_pc_cs[0];
/* t0_0 */
                                        unsigned int __cs_tmp_t1_r0;
                                        if (__cs_active_thread[1])
                                                {
                                        __cs_pc_cs[1] = __cs_tmp_t1_r0;
                                        __CPROVER_assume(__cs_pc_cs[1] <= 5);
                                        t0_0(__cs_threadargs[1]);
                                        __cs_pc[1] = __cs_pc_cs[1];
                                                }
/* t1_0 */
                                        unsigned int __cs_tmp_t2_r0;
                                        if (__cs_active_thread[2])
                                                {
                                        __cs_pc_cs[2] = __cs_tmp_t2_r0;
                                        __CPROVER_assume(__cs_pc_cs[2] <= 5);
                                        t1_0(__cs_threadargs[2]);
                                        __cs_pc[2] = __cs_pc_cs[2];
                                                }
                                        unsigned int __cs_tmp_t0_r1;
                                        if (__cs_active_thread[0] == 1)
                                                {
                                        __cs_pc_cs[0] = __cs_pc[0] + __cs_tmp_t0_r1;
                                        __CPROVER_assume(__cs_pc_cs[0] >= __cs_pc[0]);
                                        __CPROVER_assume(__cs_pc_cs[0] <= 2);
                                        main_thread();
                                                }
                                        return 0;
                                        }
                                        
